# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ADC.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ADCDialog(object):
    def setupUi(self, ADCDialog):
        ADCDialog.setObjectName("ADCDialog")
        ADCDialog.resize(227, 140)
        self.buttonBox = QtWidgets.QDialogButtonBox(ADCDialog)
        self.buttonBox.setGeometry(QtCore.QRect(50, 100, 121, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lineEdit = QtWidgets.QLineEdit(ADCDialog)
        self.lineEdit.setGeometry(QtCore.QRect(80, 10, 101, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(ADCDialog)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 71, 20))
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(ADCDialog)
        self.label_7.setGeometry(QtCore.QRect(30, 70, 41, 16))
        self.label_7.setObjectName("label_7")
        self.comboBox_2 = QtWidgets.QComboBox(ADCDialog)
        self.comboBox_2.setGeometry(QtCore.QRect(80, 70, 101, 22))
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_5 = QtWidgets.QLabel(ADCDialog)
        self.label_5.setGeometry(QtCore.QRect(20, 40, 41, 16))
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(ADCDialog)
        self.comboBox.setGeometry(QtCore.QRect(80, 40, 101, 22))
        self.comboBox.setObjectName("comboBox")

        self.retranslateUi(ADCDialog)
        self.buttonBox.accepted.connect(ADCDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ADCDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ADCDialog)

    def retranslateUi(self, ADCDialog):
        _translate = QtCore.QCoreApplication.translate
        ADCDialog.setWindowTitle(_translate("ADCDialog", "ADC"))
        self.label_3.setText(_translate("ADCDialog", "Comment:"))
        self.label_7.setText(_translate("ADCDialog", "Name:"))
        self.label_5.setText(_translate("ADCDialog", "Input"))
