# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ardIOnote.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ardIOnoteDialog(object):
    def setupUi(self, ardIOnoteDialog):
        ardIOnoteDialog.setObjectName("ardIOnoteDialog")
        ardIOnoteDialog.resize(289, 167)
        self.buttonBox = QtWidgets.QDialogButtonBox(ardIOnoteDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 120, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(ardIOnoteDialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 271, 101))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(ardIOnoteDialog)
        self.buttonBox.accepted.connect(ardIOnoteDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ardIOnoteDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ardIOnoteDialog)

    def retranslateUi(self, ardIOnoteDialog):
        _translate = QtCore.QCoreApplication.translate
        ardIOnoteDialog.setWindowTitle(_translate("ardIOnoteDialog", "Changing Hardware Error."))
        self.label.setText(_translate("ardIOnoteDialog", "There are IO, PWM ,or ADC\n"
"numbers higher than\n"
"this hardwar supports.\n"
"\n"
"Please remove those elements \n"
"before choosing this hardware. "))
