# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cont.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ContDialog(object):
    def setupUi(self, ContDialog):
        ContDialog.setObjectName("ContDialog")
        ContDialog.resize(182, 137)
        self.buttonBox = QtWidgets.QDialogButtonBox(ContDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 100, 121, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_3 = QtWidgets.QLabel(ContDialog)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 71, 20))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(ContDialog)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 50, 13))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(ContDialog)
        self.label_7.setGeometry(QtCore.QRect(10, 70, 81, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit = QtWidgets.QLineEdit(ContDialog)
        self.lineEdit.setGeometry(QtCore.QRect(70, 10, 101, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox = QtWidgets.QComboBox(ContDialog)
        self.comboBox.setGeometry(QtCore.QRect(70, 40, 101, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(ContDialog)
        self.comboBox_2.setGeometry(QtCore.QRect(70, 70, 101, 22))
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setObjectName("comboBox_2")

        self.retranslateUi(ContDialog)
        self.buttonBox.accepted.connect(ContDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ContDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ContDialog)

    def retranslateUi(self, ContDialog):
        _translate = QtCore.QCoreApplication.translate
        ContDialog.setWindowTitle(_translate("ContDialog", "Contact Properties"))
        self.label_3.setText(_translate("ContDialog", "Comment:"))
        self.label_5.setText(_translate("ContDialog", "Input"))
        self.label_7.setText(_translate("ContDialog", "Name:"))
