# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'counter.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CounterDialog(object):
    def setupUi(self, CounterDialog):
        CounterDialog.setObjectName("CounterDialog")
        CounterDialog.resize(182, 139)
        self.buttonBox = QtWidgets.QDialogButtonBox(CounterDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 100, 121, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_3 = QtWidgets.QLabel(CounterDialog)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 71, 20))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(CounterDialog)
        self.lineEdit.setGeometry(QtCore.QRect(70, 10, 101, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_7 = QtWidgets.QLabel(CounterDialog)
        self.label_7.setGeometry(QtCore.QRect(20, 70, 41, 16))
        self.label_7.setObjectName("label_7")
        self.comboBox_2 = QtWidgets.QComboBox(CounterDialog)
        self.comboBox_2.setGeometry(QtCore.QRect(70, 70, 101, 22))
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_5 = QtWidgets.QLabel(CounterDialog)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 51, 16))
        self.label_5.setObjectName("label_5")
        self.spinBox = QtWidgets.QSpinBox(CounterDialog)
        self.spinBox.setGeometry(QtCore.QRect(70, 40, 91, 22))
        self.spinBox.setMaximum(65535)
        self.spinBox.setObjectName("spinBox")

        self.retranslateUi(CounterDialog)
        self.buttonBox.accepted.connect(CounterDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(CounterDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(CounterDialog)

    def retranslateUi(self, CounterDialog):
        _translate = QtCore.QCoreApplication.translate
        CounterDialog.setWindowTitle(_translate("CounterDialog", "Counter Properties"))
        self.label_3.setText(_translate("CounterDialog", "Comment:"))
        self.label_7.setText(_translate("CounterDialog", "Name:"))
        self.label_5.setToolTip(_translate("CounterDialog", "<html><head/><body><p>maximum: 65535</p></body></html>"))
        self.label_5.setText(_translate("CounterDialog", "Setpoint"))
