# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edge.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EdgeDialog(object):
    def setupUi(self, EdgeDialog):
        EdgeDialog.setObjectName("EdgeDialog")
        EdgeDialog.resize(180, 88)
        self.buttonBox = QtWidgets.QDialogButtonBox(EdgeDialog)
        self.buttonBox.setGeometry(QtCore.QRect(20, 40, 121, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_3 = QtWidgets.QLabel(EdgeDialog)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 71, 20))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(EdgeDialog)
        self.lineEdit.setGeometry(QtCore.QRect(70, 10, 101, 20))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(EdgeDialog)
        self.buttonBox.accepted.connect(EdgeDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(EdgeDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(EdgeDialog)

    def retranslateUi(self, EdgeDialog):
        _translate = QtCore.QCoreApplication.translate
        EdgeDialog.setWindowTitle(_translate("EdgeDialog", "Edge Trigger Properties"))
        self.label_3.setText(_translate("EdgeDialog", "Comment:"))
