# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IOHelp.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IODialog(object):
    def setupUi(self, IODialog):
        IODialog.setObjectName("IODialog")
        IODialog.resize(539, 316)
        self.buttonBox = QtWidgets.QDialogButtonBox(IODialog)
        self.buttonBox.setGeometry(QtCore.QRect(200, 280, 121, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.textBrowser = QtWidgets.QTextBrowser(IODialog)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 521, 261))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(IODialog)
        self.buttonBox.accepted.connect(IODialog.accept) # type: ignore
        self.buttonBox.rejected.connect(IODialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(IODialog)

    def retranslateUi(self, IODialog):
        _translate = QtCore.QCoreApplication.translate
        IODialog.setWindowTitle(_translate("IODialog", "I/O diagram"))
