# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'math.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MathDialog(object):
    def setupUi(self, MathDialog):
        MathDialog.setObjectName("MathDialog")
        MathDialog.resize(227, 175)
        self.buttonBox = QtWidgets.QDialogButtonBox(MathDialog)
        self.buttonBox.setGeometry(QtCore.QRect(50, 140, 121, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_5 = QtWidgets.QLabel(MathDialog)
        self.label_5.setGeometry(QtCore.QRect(30, 10, 41, 16))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(MathDialog)
        self.label_7.setGeometry(QtCore.QRect(150, 10, 51, 16))
        self.label_7.setObjectName("label_7")
        self.comboBox_A = QtWidgets.QComboBox(MathDialog)
        self.comboBox_A.setGeometry(QtCore.QRect(0, 30, 101, 22))
        self.comboBox_A.setObjectName("comboBox_A")
        self.comboBox_B = QtWidgets.QComboBox(MathDialog)
        self.comboBox_B.setGeometry(QtCore.QRect(120, 30, 101, 22))
        self.comboBox_B.setEditable(False)
        self.comboBox_B.setObjectName("comboBox_B")
        self.label_8 = QtWidgets.QLabel(MathDialog)
        self.label_8.setGeometry(QtCore.QRect(90, 6, 51, 20))
        self.label_8.setObjectName("label_8")
        self.spinBox_A = QtWidgets.QSpinBox(MathDialog)
        self.spinBox_A.setGeometry(QtCore.QRect(0, 80, 101, 22))
        self.spinBox_A.setMinimum(-32767)
        self.spinBox_A.setMaximum(32767)
        self.spinBox_A.setObjectName("spinBox_A")
        self.spinBox_B = QtWidgets.QSpinBox(MathDialog)
        self.spinBox_B.setGeometry(QtCore.QRect(120, 80, 101, 22))
        self.spinBox_B.setMinimum(-32767)
        self.spinBox_B.setMaximum(32767)
        self.spinBox_B.setProperty("value", 0)
        self.spinBox_B.setObjectName("spinBox_B")
        self.label_6 = QtWidgets.QLabel(MathDialog)
        self.label_6.setGeometry(QtCore.QRect(20, 60, 51, 16))
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(MathDialog)
        self.label_9.setGeometry(QtCore.QRect(140, 60, 51, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(MathDialog)
        self.label_10.setGeometry(QtCore.QRect(30, 110, 21, 20))
        self.label_10.setObjectName("label_10")
        self.comboBox_2 = QtWidgets.QComboBox(MathDialog)
        self.comboBox_2.setGeometry(QtCore.QRect(60, 110, 101, 22))
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setObjectName("comboBox_2")

        self.retranslateUi(MathDialog)
        self.buttonBox.accepted.connect(MathDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(MathDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MathDialog)

    def retranslateUi(self, MathDialog):
        _translate = QtCore.QCoreApplication.translate
        MathDialog.setWindowTitle(_translate("MathDialog", "Math Operator"))
        self.label_5.setText(_translate("MathDialog", "Source"))
        self.label_7.setText(_translate("MathDialog", "Source"))
        self.label_8.setText(_translate("MathDialog", "(+,-,x,÷)"))
        self.label_6.setText(_translate("MathDialog", "Constant"))
        self.label_9.setText(_translate("MathDialog", "Constant"))
        self.label_10.setText(_translate("MathDialog", "="))
