# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'move.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MoveDialog(object):
    def setupUi(self, MoveDialog):
        MoveDialog.setObjectName("MoveDialog")
        MoveDialog.resize(227, 144)
        self.buttonBox = QtWidgets.QDialogButtonBox(MoveDialog)
        self.buttonBox.setGeometry(QtCore.QRect(50, 110, 121, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_5 = QtWidgets.QLabel(MoveDialog)
        self.label_5.setGeometry(QtCore.QRect(30, 10, 41, 16))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(MoveDialog)
        self.label_7.setGeometry(QtCore.QRect(150, 10, 51, 16))
        self.label_7.setObjectName("label_7")
        self.comboBox_A = QtWidgets.QComboBox(MoveDialog)
        self.comboBox_A.setGeometry(QtCore.QRect(0, 30, 101, 22))
        self.comboBox_A.setObjectName("comboBox_A")
        self.comboBox_B = QtWidgets.QComboBox(MoveDialog)
        self.comboBox_B.setGeometry(QtCore.QRect(120, 30, 101, 22))
        self.comboBox_B.setEditable(False)
        self.comboBox_B.setObjectName("comboBox_B")
        self.label_8 = QtWidgets.QLabel(MoveDialog)
        self.label_8.setGeometry(QtCore.QRect(110, 10, 16, 16))
        self.label_8.setObjectName("label_8")
        self.spinBox_A = QtWidgets.QSpinBox(MoveDialog)
        self.spinBox_A.setGeometry(QtCore.QRect(0, 80, 101, 22))
        self.spinBox_A.setMinimum(-32767)
        self.spinBox_A.setMaximum(32767)
        self.spinBox_A.setObjectName("spinBox_A")
        self.spinBox_B = QtWidgets.QSpinBox(MoveDialog)
        self.spinBox_B.setGeometry(QtCore.QRect(120, 80, 101, 22))
        self.spinBox_B.setMinimum(-32767)
        self.spinBox_B.setMaximum(32767)
        self.spinBox_B.setProperty("value", 0)
        self.spinBox_B.setObjectName("spinBox_B")
        self.label_6 = QtWidgets.QLabel(MoveDialog)
        self.label_6.setGeometry(QtCore.QRect(20, 60, 51, 16))
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(MoveDialog)
        self.label_9.setGeometry(QtCore.QRect(140, 60, 51, 16))
        self.label_9.setObjectName("label_9")

        self.retranslateUi(MoveDialog)
        self.buttonBox.accepted.connect(MoveDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(MoveDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MoveDialog)

    def retranslateUi(self, MoveDialog):
        _translate = QtCore.QCoreApplication.translate
        MoveDialog.setWindowTitle(_translate("MoveDialog", "Move"))
        self.label_5.setText(_translate("MoveDialog", "Source"))
        self.label_7.setText(_translate("MoveDialog", "Source"))
        self.label_8.setText(_translate("MoveDialog", "= "))
        self.label_6.setText(_translate("MoveDialog", "Constant"))
        self.label_9.setText(_translate("MoveDialog", "Constant"))
