# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PWM.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PWMDialog(object):
    def setupUi(self, PWMDialog):
        PWMDialog.setObjectName("PWMDialog")
        PWMDialog.resize(217, 140)
        self.buttonBox = QtWidgets.QDialogButtonBox(PWMDialog)
        self.buttonBox.setGeometry(QtCore.QRect(40, 100, 121, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(PWMDialog)
        self.doubleSpinBox.setGeometry(QtCore.QRect(80, 40, 101, 22))
        self.doubleSpinBox.setDecimals(1)
        self.doubleSpinBox.setSingleStep(0.2)
        self.doubleSpinBox.setProperty("value", 50.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.label_6 = QtWidgets.QLabel(PWMDialog)
        self.label_6.setGeometry(QtCore.QRect(10, 40, 61, 16))
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(PWMDialog)
        self.label_9.setGeometry(QtCore.QRect(190, 40, 20, 20))
        self.label_9.setObjectName("label_9")
        self.comboBox = QtWidgets.QComboBox(PWMDialog)
        self.comboBox.setGeometry(QtCore.QRect(80, 70, 101, 22))
        self.comboBox.setObjectName("comboBox")
        self.label_5 = QtWidgets.QLabel(PWMDialog)
        self.label_5.setGeometry(QtCore.QRect(20, 70, 41, 16))
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(PWMDialog)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 71, 20))
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(PWMDialog)
        self.lineEdit.setGeometry(QtCore.QRect(80, 10, 101, 20))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(PWMDialog)
        self.buttonBox.accepted.connect(PWMDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(PWMDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(PWMDialog)

    def retranslateUi(self, PWMDialog):
        _translate = QtCore.QCoreApplication.translate
        PWMDialog.setWindowTitle(_translate("PWMDialog", "PWM"))
        self.label_6.setText(_translate("PWMDialog", "Duty Cycle"))
        self.label_9.setText(_translate("PWMDialog", "%"))
        self.label_5.setText(_translate("PWMDialog", "Output"))
        self.label_4.setText(_translate("PWMDialog", "Comment:"))
