# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timer.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TimerDialog(object):
    def setupUi(self, TimerDialog):
        TimerDialog.setObjectName("TimerDialog")
        TimerDialog.resize(183, 138)
        self.buttonBox = QtWidgets.QDialogButtonBox(TimerDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 100, 121, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_3 = QtWidgets.QLabel(TimerDialog)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 71, 20))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(TimerDialog)
        self.lineEdit.setGeometry(QtCore.QRect(70, 10, 101, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_5 = QtWidgets.QLabel(TimerDialog)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 61, 21))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(TimerDialog)
        self.label_7.setGeometry(QtCore.QRect(10, 70, 41, 16))
        self.label_7.setObjectName("label_7")
        self.comboBox_2 = QtWidgets.QComboBox(TimerDialog)
        self.comboBox_2.setGeometry(QtCore.QRect(70, 70, 101, 22))
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setObjectName("comboBox_2")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(TimerDialog)
        self.doubleSpinBox.setGeometry(QtCore.QRect(80, 40, 91, 22))
        self.doubleSpinBox.setToolTip("")
        self.doubleSpinBox.setMinimum(0.01)
        self.doubleSpinBox.setMaximum(655.34)
        self.doubleSpinBox.setSingleStep(0.01)
        self.doubleSpinBox.setObjectName("doubleSpinBox")

        self.retranslateUi(TimerDialog)
        self.buttonBox.accepted.connect(TimerDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(TimerDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(TimerDialog)

    def retranslateUi(self, TimerDialog):
        _translate = QtCore.QCoreApplication.translate
        TimerDialog.setWindowTitle(_translate("TimerDialog", "Timer Properties"))
        self.label_3.setText(_translate("TimerDialog", "Comment:"))
        self.label_5.setToolTip(_translate("TimerDialog", "<html><head/><body><p>10 min. max</p></body></html>"))
        self.label_5.setText(_translate("TimerDialog", "Sec delay:"))
        self.label_7.setText(_translate("TimerDialog", "Name:"))
        self.doubleSpinBox.setToolTip(_translate("TimerDialog", "<html><head/><body><p>10 miniutes max</p></body></html>"))
