# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'USBHelp.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_USBDialog(object):
    def setupUi(self, USBDialog):
        USBDialog.setObjectName("USBDialog")
        USBDialog.resize(539, 316)
        self.buttonBox = QtWidgets.QDialogButtonBox(USBDialog)
        self.buttonBox.setGeometry(QtCore.QRect(200, 280, 121, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.textBrowser = QtWidgets.QTextBrowser(USBDialog)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 521, 261))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(USBDialog)
        self.buttonBox.accepted.connect(USBDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(USBDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(USBDialog)

    def retranslateUi(self, USBDialog):
        _translate = QtCore.QCoreApplication.translate
        USBDialog.setWindowTitle(_translate("USBDialog", "USB udev rules instructions"))
